### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by steom** [xutianyi1999/fubuki#1]
Please consider to release the windows binaries

**Comment by xutianyi1999** [comment]
https://github.com/xutianyi1999/fubuki/releases/tag/v0.4


Due to platform dependencies, this is not the best version and will not use AES-NI

**Comment by steom** [comment]
fubuki info

{
  "172.168.0.10": [
    {
      "id": 2971421372,
      "tun_addr": "172.168.0.10",
      "lan_udp_addr": null,
      "wan_udp_addr": null,
      "mode": "TCP_ONLY",
      "register_time": "2022-03-24 18:55:31",
      "direct": true
    },
    {
      "id": 692530800,
      "tun_addr": "172.168.0.20",
      "lan_udp_addr": null,
      "wan_udp_addr": null,
      "mode": "TCP_ONLY",
      "register_time": "2022-03-24 18:55:44",
      "direct": false
    }
  ]
}

the clients ping each other, but no tcp connection is possible.

server is on a public ip address and is needed to work as relay, the clients in two separated lan


‎lan_ip_addr and ‎try_send_to_lan_addr options it's not very clear for me

**Comment by xutianyi1999** [comment]
lan_ip_addr and ‎try_send_to_lan_addr are only valid when the udp option is enabled. The function is to send packets to each other's LAN address when two nodes are in the same LAN

**Comment by xutianyi1999** [comment]
try_send_to_lan_addr is false, it will only send packets to the wan address

**Comment by steom** [comment]
I tried all the possible options combinations.
I use tcp_only. 
Lan and Wan addresses is "null" as show from "info"
Now I try with 0.41

**Comment by xutianyi1999** [comment]
`TCP_ONLY` option will only relay, does not rely on wan and lan information

**Comment by steom** [comment]
in the windows 0.40 binaries the server don't relay tcp, the clients tun interface only reply to ping

**Comment by xutianyi1999** [comment]
only packets sent to the peer node TUN address will be routed

**Comment by steom** [comment]
fubuki info

{
"172.168.0.10": [
{
"id": 2971421372,
"tun_addr": "172.168.0.10",
"lan_udp_addr": null,
"wan_udp_addr": null,
"mode": "TCP_ONLY",
"register_time": "2022-03-24 18:55:31",
"direct": true
},
{
"id": 692530800,
"tun_addr": "172.168.0.20",
"lan_udp_addr": null,
"wan_udp_addr": null,
"mode": "TCP_ONLY",
"register_time": "2022-03-24 18:55:44",
"direct": false
}
]
}

Ping 172.168.0.10 works
Ping 172.168.0.20 works
Rdesktop 172.168.0.10 don't works
Rdesktop 172.168.0.20 don't works
Smb unc \\172.168.0.10 don't works
Smb unc \\172.168.0.20 don't works

Seems that the server only relay icmp traffic

**Comment by xutianyi1999** [comment]
try turning off the firewall, maybe you can use the socket tool to test first, I will add some more detailed logs later

**Comment by steom** [comment]
Obviously there is no problem at endpoint... the firewall is off.... It's only with fubuki that clients don't communicate

**Comment by xutianyi1999** [comment]
172.168.0.10 create TCP socket server, 172.168.0.20 create TCP socket client connect to 172.168.0.10,
try connection test

**Comment by xutianyi1999** [comment]
problem found, please use the intranet address for TUN address such as 192.168.1.100, mask 255.255.255.0

**Comment by xutianyi1999** [comment]
and do not conflict with network range in the local routing table

**Comment by steom** [comment]
PEER A TUN: "192.168.1.110": [
  {
    "id": 2548999157,
    "tun_addr": "192.168.1.110",
    "lan_udp_addr": null,
    "wan_udp_addr": null,
    "mode": "TCP_ONLY",
    "register_time": "2022-03-27 12:17:34",
    "direct": true
  },
  {
    "id": 2876165054,
    "tun_addr": "192.168.1.120",
    "lan_udp_addr": null,
    "wan_udp_addr": null,
    "mode": "TCP_ONLY",
    "register_time": "2022-03-27 12:17:43",
    "direct": false


 PEER B TUN "192.168.1.120": [
    {
      "id": 2876165054,
      "tun_addr": "192.168.1.120",
      "lan_udp_addr": null,
      "wan_udp_addr": null,
      "mode": "TCP_ONLY",
      "register_time": "2022-03-27 12:17:43",
      "direct": true
    },
    {
      "id": 2548999157,
      "tun_addr": "192.168.1.110",
      "lan_udp_addr": null,
      "wan_udp_addr": null,
      "mode": "TCP_ONLY",
      "register_time": "2022-03-27 12:17:34",
      "direct": false
    }

same problem... maybe with a new build?

**Comment by xutianyi1999** [comment]
....I will release a new version later, if possible, please try some socket tools to test if it can work properly, 192.168.1.110 to create a TCP server, 192.168.1.120 to create a TCP client to connect to 192.168.1.110

**Comment by steom** [comment]
i tried with netcat.. same results... no socket connection

**Comment by xutianyi1999** [comment]
can udp packets be received?

**Comment by steom** [comment]
yes udp go trought without problems

**Comment by xutianyi1999** [comment]
https://github.com/xutianyi1999/fubuki/releases/tag/v0.4.2  add some logs
set env variable FUBUKI_LOG=DEBUG

**Comment by steom** [comment]
ok debugging allowed me to identify the problem which was exclusively  on my side.
many thanks for the support effort.
fubuki it's great (the absolute best in his league to tell the truth)! even though is still a young project.
