### ISSUE TITLE
可否增加arm平台支持

### ISSUE THREAD

**Issue by liniu** [xutianyi1999/fubuki#11]
可否增加armv7平台支持，用于nas设备，谢谢

**Comment by xutianyi1999** [comment]
我没有armv7环境，你可以fork仓库在下面添加`armv7-unknown-linux-musleabi` target，之后添加一个tag去触发action编译，如果编译能过那应该可以跑
https://github.com/xutianyi1999/fubuki/blob/3d48707c7695b840b4eb07c5dec8290a72970f11/.github/workflows/rust.yml#L21-L31



所有平台
https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by liniu** [comment]
我找个时间试一下，谢谢
