### ISSUE TITLE
routed subnet

### ISSUE THREAD

**Issue by steom** [xutianyi1999/fubuki#2]
please consider to add support to route peer subnet network range
something like wireguard AllowedIPs:

  "network_ranges": [
    {
      "server_addr": "102.129.255.0:12345",
      "tun": {
        "ip": "192.168.1.110",
        "netmask": "255.255.255.0",
        "AllowedIPs": "172.168.80.0/20"

**Comment by xutianyi1999** [comment]
maybe try adding this feature

**Comment by xutianyi1999** [comment]
This feature is added to the master branch
