### ISSUE TITLE
使用了与请求的协议不兼容的地址。 (os error 10047)

### ISSUE THREAD

**Issue by M1saka10010** [xutianyi1999/fubuki#20]
```
[2023-09-16 16:16:22] INFO fubuki::node - node M1saka-Gaming-Laptop(10.100.0.11) has joined group misaka-network
[2023-09-16 16:16:22] INFO fubuki::node - group misaka-network address range 10.100.0.0/24
[2023-09-16 16:16:22] INFO fubuki::node - node M1saka-Gaming-Laptop update hosts
[2023-09-16 16:16:25] INFO fubuki::node - node M1saka-Gaming-Laptop update hosts
[2023-09-16 16:16:30] INFO fubuki::node - clear node M1saka-Gaming-Laptop host records
[2023-09-16 16:16:30] INFO fubuki::node - clear node M1saka-Gaming-Laptop nat list
node M1saka-Gaming-Laptop udp handler error

Caused by:
    使用了与请求的协议不兼容的地址。 (os error 10047)
```

**Comment by M1saka10010** [comment]
windows日志
```
由于无法创建驱动程序设备，初始化失败。 使用字符串“000000000100320000000000D71000C013010000250200C016000000000000000000000000000000”识别初始化失败的 接口。如果 NetBT 无法从全局唯一接口标识符(GUID) 映射到 MAC 地址，则该接口表示已失败接口 或 GUID 的 MAC 地址。如果 MAC 地址或 GUID 都 不可用，字符串表示群集设备名称。 
```

**Comment by xutianyi1999** [comment]
其他机器有出现类似的错误吗，我在代码中还没有定位到问题，本机防火墙也可能导致出现这个错误

**Comment by M1saka10010** [comment]
> 其他机器有出现类似的错误吗，我在代码中还没有定位到问题，本机防火墙也可能导致出现这个错误

我两台电脑都这样，看网上教程重置了winsocks也不行

**Comment by M1saka10010** [comment]
> 其他机器有出现类似的错误吗，我在代码中还没有定位到问题，本机防火墙也可能导致出现这个错误

看起来是p2p的问题，我配置文件中删去p2p选项就能正常运行

**Comment by xutianyi1999** [comment]
server ip用的是ipv6吗

**Comment by M1saka10010** [comment]
> server ip用的是ipv6吗

ipv4,不过填的是域名
```
{
	"mtu": 1500,
	"channel_limit": 100,
	"api_addr": "127.0.0.1:3030",
	"tcp_heartbeat_interval_secs": 5,
	"udp_heartbeat_interval_secs": 5,
	"tcp_heartbeat_continuous_loss": 5,
	"udp_heartbeat_continuous_loss": 5,
	"udp_heartbeat_continuous_recv": 3,
	"reconnect_interval_secs": 3,
	"udp_socket_recv_buffer_size": 8192,
	"udp_socket_send_buffer_size": 8192,
	"groups": [
		{
			"node_name": "t1",
			"server_addr": "network.misaka.ren:23323",
			"tun_addr": {
				"ip": "10.100.0.11",
				"netmask": "255.255.255.0"
			},
			"key": "",
			"mode": {
				"p2p": ["UDP"],
				"relay": ["UDP", "TCP"]
			},
			"allowed_ips": ["192.168.1.0/24"],
			"ips": {
			}
		}
	]
}

```

**Comment by xutianyi1999** [comment]
mtu太大了，改小点试试
https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/main.rs#L296-L302

**Comment by xutianyi1999** [comment]
> mtu太大了，改小点试试
> 
> https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/main.rs#L296-L302

但这个问题应该和mtu无关

**Comment by xutianyi1999** [comment]
还是不知道问题原因，如果你那里有编译环境暂时可以先把末尾的问号去了忽略错误
https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/node/mod.rs#L548

**Comment by M1saka10010** [comment]
> 还是不知道问题原因，如果你那里有编译环境暂时可以先把末尾的问号去了忽略错误
> 
> https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/node/mod.rs#L548

本地没有rust环境emm，可以编译好了发我试试吗？

**Comment by xutianyi1999** [comment]
[[> > 还是不知道问题原因，如果你那里有编译环境暂时可以先把末尾的问号去了忽略错误
> > https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/node/mod.rs#L548
> 
> 本地没有rust环境emm，可以编译好了发我试试吗？

https://github.com/xutianyi1999/fubuki-test/releases/tag/v0.1.11

**Comment by M1saka10010** [comment]
> [[> > 还是不知道问题原因，如果你那里有编译环境暂时可以先把末尾的问号去了忽略错误
> 
> > > https://github.com/xutianyi1999/fubuki/blob/db7f03f014e4307fc02a7f81d7070ac6313ff96b/src/node/mod.rs#L548
> > 
> > 
> > 本地没有rust环境emm，可以编译好了发我试试吗？
> 
> https://github.com/xutianyi1999/fubuki-test/releases/tag/v0.1.11

报错消失了，但是p2p失败（我有一边nat1一边nat3）

**Comment by xutianyi1999** [comment]
![image](https://github.com/xutianyi1999/fubuki/assets/31791535/4f026573-0221-483f-b946-af13b7d7ae09)
能看下你的资源监视器吗

**Comment by M1saka10010** [comment]
![image](https://github.com/xutianyi1999/fubuki/assets/29598885/80d81f30-3b0e-46ac-9985-20bc01d3b294)


> ![image](https://user-images.githubusercontent.com/31791535/268565896-4f026573-0221-483f-b946-af13b7d7ae09.png) 能看下你的资源监视器吗

**Comment by xutianyi1999** [comment]
server的listen_addr用的是ipv6吗[::]，我前面自己复现了

**Comment by M1saka10010** [comment]
> server的listen_addr用的是ipv6吗[::]，我前面自己复现了

y

**Comment by xutianyi1999** [comment]
换成0.0.0.0就能解决了，这个问题后续会考虑完善

**Comment by M1saka10010** [comment]
成功了，谢谢
