### ISSUE TITLE
[feat]:可否实现定义一个中转节点，使当前客户端通过中转节点与其他节点通信？

### ISSUE THREAD

**Issue by M1saka10010** [xutianyi1999/fubuki#21]
这样可以nat3->nat1->nat4。可以实现宽带最大化利用

**Comment by xutianyi1999** [comment]
呃但是全锥形限制锥形应该都能相互p2p的，只有限制锥形与对等之间没法p2p以及对等之间

**Comment by M1saka10010** [comment]
> 呃但是全锥形限制锥形应该都能相互p2p的，只有限制锥形与对等之间没法p2p以及对等之间

哦，刚才看了下，原来我这边变成对等了LOL。

**Comment by xutianyi1999** [comment]
直接写路由表吧，用虚拟地址
NAT3 Node: route add { NAT4 Node Address } MASK 255.255.255.255 { NAT1 Node Address }
NAT4 Node: route add { NAT3 Node Address } MASK 255.255.255.255 { NAT1 Node Address }
NAT1 Node: 开启内核转发

**Comment by xutianyi1999** [comment]
nat3 node 配置文件添加
```json
"ips": {
	"{nat1 node address}": ["{nat4 node address}/32"]
}
```
nat4 node 配置文件添加
```json
"ips": {
	"{nat1 node address}": ["{nat3 node address}/32"]
}
```
nat1 node 得开内核转发，比如linux
```shell
sudo sysctl -w net.ipv4.ip_forward=1
```

**Comment by M1saka10010** [comment]
> nat3 node 配置文件添加
> 
> ```json
> "ips": {
> 	"{nat1 node address}": ["{nat4 node address}/32"]
> }
> ```
> 
> nat4 node 配置文件添加
> 
> ```json
> "ips": {
> 	"{nat1 node address}": ["{nat3 node address}/32"]
> }
> ```
> 
> nat1 node 得开内核转发，比如linux
> 
> ```shell
> sudo sysctl -w net.ipv4.ip_forward=1
> ```

成功了，感谢大佬
