### ISSUE TITLE
打洞能力很弱，需要两端都是全锥型才能p2p

### ISSUE THREAD

**Issue by 13653216371** [xutianyi1999/fubuki#22]
甲骨文服务器，如果不放开相关udp端口，是不能建立起p2p的。使用tailscale没问题。
经测试，需要两端都是全锥型才能p2p，还达不到n2n的打洞能力，虽然n2n不那么厉害，但是可以一端全锥即可p2p。

另外，建议可以指定源port，方便开放源udp端口

**Comment by xutianyi1999** [comment]
server端需要开放tcp udp两个端口，节点防火墙不需要开放端口。
节点不需要两端都全锥，两端限锥或一端全锥一端对称都能p2p。

能否再具体说明下节点结构

**Comment by 13653216371** [comment]
三台甲骨文linux，其中1台是server，2台是node，一台windows作为node测试。

我主要是在windows来看p2p状态，当我在家里的路由器做完dmz后才能建立p2p，反之不能。
期间cmd一直在弹日志udp被远程服务器关闭，不知道是否和这个有关系

**Comment by 13653216371** [comment]
> server端需要开放tcp udp两个端口，节点防火墙不需要开放端口。 节点不需要两端都全锥，两端限锥或一端全锥一端对称都能p2p。
> 
> 能否再具体说明下节点结构

server端是放行了比如3456的udp和tcp端口的

**Comment by xutianyi1999** [comment]
> 三台甲骨文linux，其中1台是server，2台是node，一台windows作为node测试。
> 
> 
> 
> 我主要是在windows来看p2p状态，当我在家里的路由器做完dmz后才能建立p2p，反之不能。
> 
> 期间cmd一直在弹日志udp被远程服务器关闭，不知道是否和这个有关系

是10054 code吗，一般重启程序就行如果还是报错的话试试windows防火墙添加对fubuki程序网络的出入栈放行

**Comment by 13653216371** [comment]
> > 三台甲骨文linux，其中1台是server，2台是node，一台windows作为node测试。
> > 我主要是在windows来看p2p状态，当我在家里的路由器做完dmz后才能建立p2p，反之不能。
> > 期间cmd一直在弹日志udp被远程服务器关闭，不知道是否和这个有关系
> 
> 是10054 code吗，一般重启程序就行如果还是报错的话试试windows防火墙添加对fubuki程序网络的出入栈放行

是的 10054 code，在windows防火墙的出方向和入方向针对fubuki.exe做了放行，仍然报错。。
[2023-11-11 22:26:51] ERROR fubuki::node - node shenzhou receive udp packet error 远程主机强迫关闭了一个现有的连接。 (os error 10054)

**Comment by xutianyi1999** [comment]
同一内网是否还有别的能测试fubuki的PC，以及尝试使用手机热点联网。
需要验证是本机还是上层路由导致的问题

**Comment by 13653216371** [comment]
> 同一内网是否还有别的能测试fubuki的PC，以及尝试使用手机热点联网。 需要验证是本机还是上层路由导致的问题

换手机热点，不报这个code了。ok
