### ISSUE TITLE
node中继功能？

### ISSUE THREAD

**Issue by 13653216371** [xutianyi1999/fubuki#23]
服务器中转延迟比较大，能否让node A根据延迟选择其他nodeX来中继去往node B的数据？

**Comment by 13653216371** [comment]
如果可以在web界面直接点击选择要中转的node就太牛逼了

**Comment by xutianyi1999** [comment]
当前版本无法实现，后续版本应该会增加该功能。
临时替代方式: #21

**Comment by 13653216371** [comment]
> 当前版本无法实现，后续版本应该会增加该功能。 临时替代方式: #21

这个解决办法，在中转节点抓包可以看到icmp重定向，来回路径不一致，而且效率并不高

**Comment by xutianyi1999** [comment]
> > 当前版本无法实现，后续版本应该会增加该功能。 临时替代方式: #21
> 
> 这个解决办法，在中转节点抓包可以看到icmp重定向，来回路径不一致，而且效率并不高

来回路径不一致是因为只改了一端节点的配置，需要双方都改
