### ISSUE TITLE
It doesn't work in win7 OS.

### ISSUE THREAD

**Issue by bigbenz8** [xutianyi1999/fubuki#27]
The program cannot be started.Error reportedError messageError message reported:
![image](https://github.com/xutianyi1999/fubuki/assets/8120813/7eecee78-851f-40f2-9c11-0b86b2c9c447)

**Comment by xutianyi1999** [comment]
Github Action上是Windows Server 2022和最新Rust编译环境，这俩编译出来的目标文件都不在兼容Win7了。
我这边也没有Win7的编译环境，目前Win7应该只能手动编译了。

**Comment by bigbenz8** [comment]
> Github Action上是Windows Server 2022和最新Rust编译环境，这俩编译出来的目标文件都不在兼容Win7了。 我这边也没有Win7的编译环境，目前Win7应该只能手动编译了。

win7现在还有一些老机器在用 ， 能兼容到win7就更好了。

**Comment by beck-8** [comment]
这年头还有用win7的

**Comment by xutianyi1999** [comment]
https://github.com/xutianyi1999/fubuki/releases/tag/v0.5.11

- Windows7 需要安装 [KB3063858](https://www.microsoft.com/en-us/download/details.aspx?id=47409)、[KB4474419](https://www.catalog.update.microsoft.com/search.aspx?q=kb4474419) 这两个补丁
