### ISSUE TITLE
address pool

### ISSUE THREAD

**Issue by steom** [xutianyi1999/fubuki#3]
please consider to add an ip address pool in the server.
when a fubuki client make a socket connection with a successful login to the fubuki server, the server pass a free ip address from the pool to the client for configure the tun.

{
  "channel_limit": 100,
  "tcp_heartbeat_interval_secs": 5,
  "ip_pool": 192.168.1.0/24,
  "listeners": [
    {
      "listen_addr": "0.0.0.0:12345",
      "key": "a123"
    }
  ]
}

**Comment by xutianyi1999** [comment]
This feature is added to the master branch
