### ISSUE TITLE
能否搞上无中心模式

### ISSUE THREAD

**Issue by 13653216371** [xutianyi1999/fubuki#30]
看到已经支持客户端中转了，很棒。
rt，能否搞上无中心模式，每台都可以作为服务器

**Comment by Musixal** [comment]
I think it's a good idea to implement decentralized mesh network instead of server-dependent network. So what's happens to other nodes if the server have some maintenance break?

**Comment by 13653216371** [comment]
可以连接任意一台节点同步其他节点的信息，这时称为服务器似乎不合适。因为每一台都是服务器

**Comment by Musixal** [comment]
To be clear what the idea of "server" mode in the fubuki? you can't just run a node without server address.  Read the "Usage" part of the readme, the server mode is mandatory. So this not a decentralized mesh network and depends to a server (or supernode)

**Comment by xutianyi1999** [comment]
目前还是很难实现，因为现在节点的所有信息交换还是通过Server来完成的

**Comment by 13653216371** [comment]
双server可行吗
