### ISSUE TITLE
可提供mac系统上的可执行文件下载吗

### ISSUE THREAD

**Issue by briteming** [xutianyi1999/fubuki#4]
如题。
非常感谢

**Comment by briteming** [comment]
https://github.com/xutianyi1999/fubuki/releases/download/v0.4.2/release.zip内没有mac系统上的可执行文件

**Comment by briteming** [comment]
hi.

on my mac.

yudeMacBook-Air:fubuki ym$ cargo build --release
显示：
    Updating crates.io index
error: failed to get `aes` as a dependency of package `fubuki v0.4.2 (/Users/ym/fubuki)`

Caused by:
  failed to load source for dependency `aes`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  error: RPC failed; result=18, HTTP code = 200
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
yudeMacBook-Air:fubuki ym$

怎么解决问题？

谢谢回复！

**Comment by xutianyi1999** [comment]
网络问题，环境变量设置代理或cargo设置代理，或者尝试用国内源。我mac在公司这两天也没法编译

**Comment by briteming** [comment]
hi.

我替cargo设置代理了：
我是在项目的根目录下，新建了 .cargo目录，然后在.cargo目录里，创建了config.toml ,

yudeMacBook-Air:fubuki ym$ ls -la
total 24
drwxr-xr-x     9 yuming  staff    306  4  4 18:46 .
drwxr-xr-x+ 1083 yuming  staff  36822  4  4 19:59 ..
drwxr-xr-x     3 yuming  staff    102  4  6 11:45 .cargo
drwxr-xr-x    13 yuming  staff    442  4  4 13:36 .git
-rw-r--r--     1 yuming  staff     40  4  3 01:18 .gitignore
-rw-r--r--     1 yuming  staff    849  4  3 01:18 Cargo.toml
-rw-r--r--     1 yuming  staff   1104  4  3 01:18 README.md
drwxr-xr-x     5 yuming  staff    170  4  3 01:18 cfg-example
drwxr-xr-x     7 yuming  staff    238  4  3 01:18 src
yudeMacBook-Air:fubuki ym$ cd .cargo
yudeMacBook-Air:.cargo ym$ ls -la
total 8
drwxr-xr-x  3 yuming  staff  102  4  6 11:45 .
drwxr-xr-x  9 yuming  staff  306  4  4 18:46 ..
-rw-r--r--  1 yuming  staff  488  4  6 11:53 config.toml
yudeMacBook-Air:.cargo ym$ cat config.toml
[build]
rustflags = "-C target-cpu=native"

[net]
retry = 2                   # network retries
git-fetch-with-cli = true

[http]
debug = false               # HTTP debugging
proxy = "http://127.0.0.1:3080"  

yudeMacBook-Air:.cargo ym$

127.0.0.1:3080是我的Mac上运行的一个http proxy, 它是正常的，可以用它来让浏览器翻墙。

难道是因为这里的config.toml的内容写错了吗？我是按https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli 写的。

**Comment by xutianyi1999** [comment]
```toml
[http]
proxy = "127.0.0.1:3080"
[https]
proxy = "127.0.0.1:3080"
```
只需要这样

**Comment by briteming** [comment]
hi.
还是不行。不过这次我设了国内源：
yudeMacBook-Air:fubuki ym$ cat .cargo/config.toml
[net]
retry = 2 # network retries
git-fetch-with-cli = true

[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'ustc'

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

yudeMacBook-Air:fubuki ym$ 
yudeMacBook-Air:fubuki ym$ cargo build --release
    Updating `ustc` index
    Updating git repository `https://github.com/xutianyi1999/SimpleWintun.git`
  Downloaded ahash v0.7.6 (registry `ustc`)
  Downloaded aes v0.8.1 (registry `ustc`)
  Downloaded anyhow v1.0.56 (registry `ustc`)
  Downloaded aho-corasick v0.7.18 (registry `ustc`)
  Downloaded autocfg v1.1.0 (registry `ustc`)
  Downloaded arc-swap v0.4.8 (registry `ustc`)
  Downloaded bytes v1.1.0 (registry `ustc`)
  Downloaded cc v1.0.73 (registry `ustc`)
  Downloaded cfg-if v1.0.0 (registry `ustc`)
  Downloaded chrono v0.4.19 (registry `ustc`)
  Downloaded cipher v0.4.3 (registry `ustc`)
  Downloaded cpufeatures v0.2.2 (registry `ustc`)
  Downloaded crossbeam-channel v0.5.4 (registry `ustc`)
  Downloaded crossbeam-utils v0.8.8 (registry `ustc`)
  Downloaded crypto-common v0.1.3 (registry `ustc`)
  Downloaded ctr v0.9.1 (registry `ustc`)
  Downloaded derivative v2.2.0 (registry `ustc`)
  Downloaded fnv v1.0.7 (registry `ustc`)
  Downloaded futures-core v0.3.21 (registry `ustc`)
  Downloaded futures-macro v0.3.21 (registry `ustc`)
  Downloaded futures-task v0.3.21 (registry `ustc`)
  Downloaded futures-util v0.3.21 (registry `ustc`)
  Downloaded generic-array v0.14.5 (registry `ustc`)
  Downloaded getrandom v0.2.6 (registry `ustc`)
  Downloaded hashbrown v0.11.2 (registry `ustc`)
  Downloaded humantime v2.1.0 (registry `ustc`)
  Downloaded indexmap v1.8.1 (registry `ustc`)
  Downloaded inout v0.1.3 (registry `ustc`)
  Downloaded instant v0.1.12 (registry `ustc`)
  Downloaded ioctl-sys v0.6.0 (registry `ustc`)
  Downloaded itoa v1.0.1 (registry `ustc`)
  Downloaded lazy_static v1.4.0 (registry `ustc`)
  Downloaded libc v0.2.121 (registry `ustc`)
  Downloaded linked-hash-map v0.5.4 (registry `ustc`)
  Downloaded libmimalloc-sys v0.1.24 (registry `ustc`)
  Downloaded lock_api v0.4.7 (registry `ustc`)
  Downloaded log v0.4.16 (registry `ustc`)
  Downloaded log-mdc v0.1.0 (registry `ustc`)
  Downloaded log4rs v1.0.0 (registry `ustc`)
  Downloaded md5 v0.7.0 (registry `ustc`)
  Downloaded memchr v2.4.1 (registry `ustc`)
  Downloaded mimalloc v0.1.28 (registry `ustc`)
  Downloaded mio v0.8.2 (registry `ustc`)
  Downloaded num-integer v0.1.44 (registry `ustc`)
  Downloaded num-traits v0.2.14 (registry `ustc`)
  Downloaded num_cpus v1.13.1 (registry `ustc`)
  Downloaded once_cell v1.10.0 (registry `ustc`)
  Downloaded ordered-float v2.10.0 (registry `ustc`)
  Downloaded parking_lot v0.11.2 (registry `ustc`)
  Downloaded parking_lot v0.12.0 (registry `ustc`)
  Downloaded parking_lot_core v0.8.5 (registry `ustc`)
  Downloaded parking_lot_core v0.9.2 (registry `ustc`)
  Downloaded pin-project-lite v0.2.8 (registry `ustc`)
  Downloaded pin-utils v0.1.0 (registry `ustc`)
  Downloaded ppv-lite86 v0.2.16 (registry `ustc`)
  Downloaded proc-macro2 v1.0.37 (registry `ustc`)
  Downloaded quote v1.0.17 (registry `ustc`)
  Downloaded rand v0.8.5 (registry `ustc`)
  Downloaded rand_chacha v0.3.1 (registry `ustc`)
  Downloaded rand_core v0.6.3 (registry `ustc`)
  Downloaded regex v1.5.5 (registry `ustc`)
  Downloaded regex-syntax v0.6.25 (registry `ustc`)
  Downloaded ryu v1.0.9 (registry `ustc`)
  Downloaded scopeguard v1.1.0 (registry `ustc`)
  Downloaded serde v1.0.136 (registry `ustc`)
  Downloaded serde-value v0.7.0 (registry `ustc`)
  Downloaded serde_derive v1.0.136 (registry `ustc`)
  Downloaded serde_json v1.0.79 (registry `ustc`)
  Downloaded serde_yaml v0.8.23 (registry `ustc`)
  Downloaded signal-hook-registry v1.4.0 (registry `ustc`)
  Downloaded slab v0.4.6 (registry `ustc`)
  Downloaded smallvec v1.8.0 (registry `ustc`)
  Downloaded socket2 v0.4.4 (registry `ustc`)
  Downloaded syn v1.0.91 (registry `ustc`)
  Downloaded thiserror v1.0.30 (registry `ustc`)
  Downloaded thiserror-impl v1.0.30 (registry `ustc`)
  Downloaded thread-id v3.3.0 (registry `ustc`)
  Downloaded time v0.1.43 (registry `ustc`)
  Downloaded tokio-macros v1.7.0 (registry `ustc`)
  Downloaded traitobject v0.1.0 (registry `ustc`)
  Downloaded tokio v1.17.0 (registry `ustc`)
  Downloaded tun v0.5.3 (registry `ustc`)
  Downloaded typemap v0.3.3 (registry `ustc`)
  Downloaded typenum v1.15.0 (registry `ustc`)
  Downloaded unicode-xid v0.2.2 (registry `ustc`)
  Downloaded unsafe-any v0.4.2 (registry `ustc`)
  Downloaded version_check v0.9.4 (registry `ustc`)
  Downloaded yaml-rust v0.4.5 (registry `ustc`)
  Downloaded 88 crates (5.9 MB) in 3m 36s (largest was `libmimalloc-sys` at 1.1 MB)
   Compiling libc v0.2.121
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.37
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.91
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling serde_derive v1.0.136
   Compiling serde v1.0.136
   Compiling typenum v1.15.0
   Compiling memchr v2.4.1
   Compiling smallvec v1.8.0
   Compiling log v0.4.16
   Compiling scopeguard v1.1.0
   Compiling parking_lot_core v0.8.5
   Compiling cc v1.0.73
   Compiling parking_lot_core v0.9.2
   Compiling hashbrown v0.11.2
   Compiling traitobject v0.1.0
   Compiling ryu v1.0.9
   Compiling crossbeam-utils v0.8.8
   Compiling serde_json v1.0.79
   Compiling futures-core v0.3.21
   Compiling futures-task v0.3.21
   Compiling linked-hash-map v0.5.4
   Compiling anyhow v1.0.56
   Compiling futures-util v0.3.21
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.10.0
   Compiling regex-syntax v0.6.25
   Compiling pin-project-lite v0.2.8
   Compiling ppv-lite86 v0.2.16
   Compiling itoa v1.0.1
   Compiling pin-utils v0.1.0
   Compiling slab v0.4.6
   Compiling humantime v2.1.0
   Compiling fnv v1.0.7
   Compiling cpufeatures v0.2.2
   Compiling arc-swap v0.4.8
   Compiling bytes v1.1.0
   Compiling log-mdc v0.1.0
   Compiling ioctl-sys v0.6.0
   Compiling md5 v0.7.0
   Compiling num-traits v0.2.14
   Compiling lock_api v0.4.7
   Compiling indexmap v1.8.1
   Compiling num-integer v0.1.44
   Compiling instant v0.1.12
   Compiling generic-array v0.14.5
   Compiling ahash v0.7.6
   Compiling unsafe-any v0.4.2
   Compiling yaml-rust v0.4.5
   Compiling libmimalloc-sys v0.1.24
   Compiling typemap v0.3.3
The following warnings were emitted during compilation:

warning: In file included from c_src/mimalloc/src/static.c:24:
warning: In file included from c_src/mimalloc/src/random.c:198:
warning: /usr/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
warning: typedef CCCryptorStatus CCRNGStatus;
warning:         ^
warning: 1 error generated.

error: failed to run custom build command for `libmimalloc-sys v0.1.24`

Caused by:
  process didn't exit successfully: `/Users/ym/fubuki/target/release/build/libmimalloc-sys-3951059f7f3ba385/build-script-build` (exit status: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/Users/ym/fubuki/target/release/build/libmimalloc-sys-c425d57c0d514d12/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c"
  cargo:warning=In file included from c_src/mimalloc/src/static.c:24:
  cargo:warning=In file included from c_src/mimalloc/src/random.c:198:
  cargo:warning=/usr/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
  cargo:warning=typedef CCCryptorStatus CCRNGStatus;
  cargo:warning=        ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-ftls-model=initial-exec" "-DMI_DEBUG=0" "-o" "/Users/ym/fubuki/target/release/build/libmimalloc-sys-c425d57c0d514d12/out/c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
yudeMacBook-Air:fubuki ym$

怎么解决这些错误？

**Comment by xutianyi1999** [comment]
emmm...只能先移除mimalloc依赖

删除
https://github.com/xutianyi1999/fubuki/blob/6d294395e9088d14b422ca5eaede6198793e2c63/Cargo.toml#L20
https://github.com/xutianyi1999/fubuki/blob/6d294395e9088d14b422ca5eaede6198793e2c63/src/main.rs#L15
https://github.com/xutianyi1999/fubuki/blob/6d294395e9088d14b422ca5eaede6198793e2c63/src/main.rs#L30
https://github.com/xutianyi1999/fubuki/blob/6d294395e9088d14b422ca5eaede6198793e2c63/src/main.rs#L31

**Comment by briteming** [comment]
hi.
这次，可成功生成fubuki.不过，

yudeMacBook-Air:release ym$ ls
build			examples		incremental
client-conf.json	fubuki
deps			fubuki.d
yudeMacBook-Air:release ym$ cat client-conf.json
{
  "mtu": 1200,
  "channel_limit": 100,
  "api_addr": "127.0.0.1:3030",
  "tcp_heartbeat_interval_secs": 5,
  "udp_heartbeat_interval_secs": 5,
  "reconnect_interval_secs": 3,
  "udp_socket_recv_buffer_size": 8192,
  "udp_socket_send_buffer_size": 8192,
  "tun_handler_thread_count": 1,
  "udp_handler_thread_count": 1,
  "network_ranges": [
    {
      "server_addr": "my-vps-public-ip:4368",
      "tun": {
        "ip": "10.0.0.1",
        "netmask": "255.255.255.0"
      },
      "key": "mykey",
      "mode": "UDP_AND_TCP",
      "lan_ip_addr": "10.0.0.2",
      "try_send_to_lan_addr": false
    }
  ]
}

yudeMacBook-Air:release ym$ ./fubuki client client-conf.json
[Console] 2022-04-06 21:47:57 - ERROR - Process error -> Failed to create UDP socket

Caused by:
    Can't assign requested address (os error 49)
yudeMacBook-Air:release ym$ sudo ./fubuki client client-conf.json
Password:
[Console] 2022-04-06 21:48:12 - ERROR - Process error -> Failed to create UDP socket

Caused by:
    Can't assign requested address (os error 49)
yudeMacBook-Air:release ym$

怎么解决？
谢谢回复。

**Comment by xutianyi1999** [comment]
去除lan_ip_addr或者正确配置，这个选项填的是你本机网卡地址

**Comment by briteming** [comment]
你这程序能用来翻墙吗

**Comment by xutianyi1999** [comment]
....你可以自行尝试搭配其他代理软件

**Comment by briteming** [comment]
hi.

能否开发一个专门用于翻墙的基于rust的VPN 程序？
