### ISSUE TITLE
 ERROR fubuki - Process error -> Failed create tun adapter

### ISSUE THREAD

**Issue by superway117** [xutianyi1999/fubuki#5]
i run it in window , post this error message, how to fix it ? already put wintun.dll into the execute folder

**Comment by xutianyi1999** [comment]
Are there more logs

**Comment by superway117** [comment]
fubuki\target\debug>fubuki.exe client ../../cfg-example/client-conf.json
Some(192.168.1.5)
1111 1462
windows 1462
11111
[2023-03-12 20:42:32] ERROR fubuki - Process error -> Failed create tun adapter

Caused by:
    %1 不是有效的 Win32 应用程序。 (os error 193)

**Comment by xutianyi1999** [comment]
确认一下wintun.dll 是amd64吗
