### ISSUE TITLE
ERROR fubuki - Process error -> Failed to create UDP socket

### ISSUE THREAD

**Issue by liniu** [xutianyi1999/fubuki#8]
fubuki client client-config.json
[2023-05-04 17:32:06] ERROR fubuki - Process error -> Failed to create UDP socket

Caused by:
    在其上下文中，该请求的地址无效。 (os error 10049)

当前目录下有wintun.dll amd64 ,但是报这个是什么问题，试过两台电脑都一样

**Comment by xutianyi1999** [comment]
删掉`lan_ip_addr`配置项，或设置成本机网卡地址

**Comment by liniu** [comment]
谢谢，搞定
